export const INPUT_ITEM_INFO = "input_item_info"
export const ADD_LIST_ITEM = "add_list_item"
export const DELETE_LIST_ITEM = "delete_list_item"
export const INIT_LIST_DATA = "init_list_data"
export const INIT_LIST_DATA_SAGA = "init_list_data_saga"
